# Generated by Django 4.0 on 2022-02-11 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_project', models.CharField(max_length=32, unique=True)),
                ('link_to_repo', models.URLField(blank=True)),
                ('list_of_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_of_todo', models.TextField()),
                ('data_time', models.DateTimeField(auto_now_add=True)),
                ('data_time_update', models.DateTimeField(auto_now_add=True)),
                ('is_active_of_todo', models.BooleanField(default=True)),
                ('author_of_todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user')),
                ('name_of_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noteapp.project')),
            ],
        ),
    ]
