# Generated by Django 4.0 on 2022-02-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name_of_project',
            field=models.CharField(max_length=32, unique=True, verbose_name='project name'),
        ),
        migrations.AlterField(
            model_name='todonote',
            name='text_of_todo',
            field=models.TextField(verbose_name='text of note'),
        ),
    ]
